/*
When a web page is loaded, the browser creates a Document Object Model of the page.
The Document Object Model (DOM) is the data representation of the objects that comprise the structure and content of a document on the web. 
It is created by the browser as the html loads into the browser.
Browser creates object of html called 'document object'
In Document object there is model of complete html in Tree like structure
*/